name = "AoC2023"
version = "0.1.0"
license = "license"
author = "Zdenek Grof"
maintainer = "zdenek.grof@vscht.cz"
copyright = "Copyright 2023, Zdenek Grof"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

